; Listing generated by Microsoft (R) Optimizing Compiler Version 17.00.60315.1 

include listing.inc

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

PUBLIC	combine4
PUBLIC	__xmm@3f800000000000000000000000000000
EXTRN	_fltused:DWORD
;	COMDAT __xmm@3f800000000000000000000000000000
CONST	SEGMENT
__xmm@3f800000000000000000000000000000 DB 00H, 00H, 00H, 00H, 00H, 00H, 00H
	DB	00H, 00H, 00H, 00H, 00H, 00H, 00H, 080H, '?'
CONST	ENDS
; Function compile flags: /Ogtpy
;	COMDAT combine4
_TEXT	SEGMENT
data$ = 8
combine4 PROC						; COMDAT
; File h:\opensource\misc\samples\csapp_assembly\combine.c
; Line 2
	movaps	xmm1, XMMWORD PTR __xmm@3f800000000000000000000000000000
	xorps	xmm2, xmm2
	add	rcx, 16
	mov	eax, 8388608				; 00800000H
	npad	13
$LL3@combine4:
; Line 6
	movups	xmm0, XMMWORD PTR [rcx-16]
	add	rcx, 64					; 00000040H
	addps	xmm1, xmm0
	movups	xmm0, XMMWORD PTR [rcx-64]
	addps	xmm2, xmm0
	movups	xmm0, XMMWORD PTR [rcx-48]
	addps	xmm1, xmm0
	movups	xmm0, XMMWORD PTR [rcx-32]
	addps	xmm2, xmm0
	dec	rax
	jne	SHORT $LL3@combine4
; Line 9
	addps	xmm1, xmm2
	movaps	xmm0, xmm1
	movhlps	xmm0, xmm1
	addps	xmm0, xmm1
	movaps	xmm1, xmm0
	shufps	xmm1, xmm0, 245				; 000000f5H
	addss	xmm0, xmm1
	ret	0
combine4 ENDP
_TEXT	ENDS
END
